### ISSUE TITLE
Detailed endpoint description

### ISSUE THREAD

**Issue by Sjimooon** [Mike-Mortensen-Portfolio/PubHub_H6_Final#33]
See [req. 8.3.a](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.fnr16imwb5tf).

This includes also adding the missing Endpoint table overviews that we made in #31

**Comment by jeongoks** [comment]
Closes #37 
Closes #93 

- I've added links to the overview tables as seen [here](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/wiki/Api-Documentation#api-endpoints-overview). So that somebody needing further explanations will be taken there.
- Then I've in added a new page of the wiki with more descriptive words about the Api endpoints with examples of the data values needed as seen [here](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/wiki/Api-endpoints-in-details).
